### ISSUE TITLE
Getting One Dependency 

### ISSUE THREAD

**Issue by bwagner5** [ilikeorangutans/grails-service-visualizer#1]
I tried the utility on two of my Grails projects and am only getting one dependency arrow from LoginController to SpringSecurityService on both. The utility picks up all the services and controllers and displays them, but does not show any dependencies. 

I have a service in the LoginController on one of my apps right below the def springSecurityService, def emailService and it doesn't pick that dependency up either (even though it does list the EmailService as a service on the graph). One of the graphs is listed below. Let me know if you have any thoughts on the issue.

![sopsgraph](https://cloud.githubusercontent.com/assets/3503707/2884606/3222dbbc-d4ae-11e3-8163-b20601983845.png)

**Comment by ilikeorangutans** [comment]
Hey,

If you could send me the service definition part of the files in question I'll take a look. :) Maybe send me the LoginController file or the generated dot file.

**Comment by bwagner5** [comment]
Works very well now. Thanks!

**Comment by ilikeorangutans** [comment]
Awesome! Mind sending me the diagram? I'm curious what it looks like! :)

On Mon, May 5, 2014 at 10:25 PM, Brandon Wagner notifications@github.comwrote:

> Closed #1https://github.com/ilikeorangutans/grails-service-visualizer/issues/1
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ilikeorangutans/grails-service-visualizer/issues/1#event-118088230
> .

## 

Cheers,
Jakob

**Comment by bwagner5** [comment]
Here's one. Quite a bit smaller than the ones you have posted, but it 
does the job.

-Brandon

**Comment by ilikeorangutans** [comment]
Hmm, sadly that didn't come through.
